Repository thoth-station/notebooks, pull requests merged in 2019-03, with the labels that each got.

#22 Default to Python 3.6 on local installation
  install.sh
Labels: approved, size/XS

#23 Add more details on how to use JanusGraph locally
  notebooks/Running JanusGraph locally.ipynb
Labels: size/L

#24 Add notebook for lockdown example
  notebooks/Thoth 0.5.0 - Example 1 Guided Notebook.ipynb
Labels: size/XL, size/XXL

#25 Increase number of open files to avoid errors
  run.sh
Labels: size/XS

#26 Make token empty by default
  run.sh
Labels: size/XS

#28 Add notebook explaining scoring scenario
  notebooks/Thoth 0.5.0 - Example 3 Guided Notebook.ipynb
Labels: size/XL, size/XXL

#29 Replay lockdown notebook to respect latest API changes
  notebooks/Thoth 0.5.0 - Example 1 Guided Notebook.ipynb
Labels: size/XL

#30 Improve run.sh script
  README.rst
  run.sh
Labels: approved, size/L

#34 Add example 3 notebook
  notebooks/Thoth 0.5.0 - Example 3 Guided Notebook.ipynb
Labels: size/XL
