Repository thoth-station/notebooks, pull requests merged in 2020-01, with the labels that each got.

#57 Adviser workflow notebook
  notebooks/workflows/adviser-inspection-workflow.ipynb
Labels: approved, size/L

#60 Add notebook for solver error classification
  notebooks/development/Solver error classification.ipynb
Labels: approved, size/XL

#61 Adjust function and name
  notebooks/workflows/adviser-workflow.ipynb
  notebooks/workflows/solver-workflow.ipynb
Labels: approved, size/M
